# Use Python 3.10 slim image
FROM python:3.10-slim

# Set environment variables
ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1

# Set working directory
WORKDIR /app

# Install pipenv and dependencies
RUN pip install --upgrade pip && \
    pip install pipenv

# Copy Pipfile and Pipfile.lock
COPY Pipfile Pipfile.lock ./

# Install dependencies
RUN pipenv install --system --deploy

# Copy source code and data
COPY src/ ./src/
COPY data/ ./data/

# Set the working directory to /app/src
WORKDIR /app/src

# Run the initialization script
CMD ["python", "initializing_application.py"]